version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: h5regmanual1653298546.azurecr.io/h5-backend:v10
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    ports:
      - "8000:8000"
